### ISSUE TITLE
Maybe “config.start_epoch” should change into “epoch” in test.py(lines 78,80,82,84,86)？

### ISSUE THREAD

**Issue by huqiaoping** [ZhiwenShao/ADLD#2]
file: test.py
lines: 78~86
**config.start_epoch** should be **epoch**?

**Comment by ZhiwenShao** [comment]
Thanks a lot. It has been fixed.

**Comment by huqiaoping** [comment]
And test.py line 110 start_epoch default should be 1. :)

**Comment by ZhiwenShao** [comment]
OK, fixed.
