### ISSUE TITLE
A conflict in landmark location refinement (codes vs. paper)

### ISSUE THREAD

**Issue by huqiaoping** [ZhiwenShao/ADLD#3]
Hi,
Thanks for your codes!
I notice in the paper you said in Fig. 3, it should have only **10** refined landmarks. But in the codes, pre_process.py lines: 69-80, totally **12**  refined landmarks. (maybe you should modify your description and your Fig. 3 in the paper? It seems that the line 77 and line 78 were not count.)

**Comment by ZhiwenShao** [comment]
We actually refine the locations of 12 landmarks, in which the landmarks 15 and 17 are refined to the centers of AU 9 (Nose Wrinkler). Note that the center locations of AU 9 is not defined by EAC-Net, which causes us ignoring this new definition.  We will revise Fig. 3 in our paper.

**Comment by huqiaoping** [comment]
Thanks. I see.
