### ISSUE TITLE
A conflict about loss_au in codes and paper

### ISSUE THREAD

**Issue by huqiaoping** [ZhiwenShao/ADLD#4]
Hi,

I note that in the paper, to compute au detection loss $L_a$, $F_a$ is only applied to $\tilde{x^t}$, as shown in Eq. 8.  But in your codes,  it seems that $L_a$ comes from two parts (train.py, line 367), one is when $F_a$ is applied to $\tilde{x^t}$ (train.py, line 358, loss_new_gen_au_tgt ), another one is when  $F_a$ is applied to $x^s$ (train.py, line 350, loss_base_gen_au_src ).  

Am I right?

I think maybe you need to revise this part in your paper. ^_^

**Comment by ZhiwenShao** [comment]
In Section 3.3, we state that "In our ADLD framework, the losses introduced above
are applied for both source and target domains. Specifically, Ll(Fl,XS,YS) and Ll(Fl,XT,YT) are used for training Fl, and Ll(Fl, ˜XS,YT) and Ll(Fl, ˜XT,YS) are only used for constraining the generation of ˜xs and ˜xt. La(Fa,XS, PS) and La(Fa, ˜XT, PS) are used for training Fa. Other losses defined in Eqs. (2), (9), (10), (11) are also applied to the source domain."
There is no conflict between the code and our paper.

**Comment by huqiaoping** [comment]
Oh, sorry I didn't see that. I see now. Thanks very much!
